/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao.menus;

import VO.ContaVO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import regraNegocio.ContaRN;
import visao.TelaPrincipalVisao;

/**
 *
 * @author narja
 */
public class MenuLogin extends FormTemplateMenus implements ActionListener {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuLogin.class.getName());
    MenuInicial MenuInicial;

    /**
     * Creates new form MenuIniciar
     */
    public MenuLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        lbCPF = new javax.swing.JLabel();
        ftCPF = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbSenha = new javax.swing.JLabel();
        pfSenha = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("LOGIN");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbCPF.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lbCPF.setText("CPF:");

        try {
            ftCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftCPFFocusGained(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lbSenha.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lbSenha.setText("SENHA:");

        pfSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfSenhaFocusGained(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCPF)
                            .addComponent(lbSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSenha))
                .addGap(56, 56, 56)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ftCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftCPFFocusGained
        ftCPF.setValue(null);
        ftCPF.setText("");
    }//GEN-LAST:event_ftCPFFocusGained

    private void pfSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfSenhaFocusGained
        pfSenha.setText("");
    }//GEN-LAST:event_pfSenhaFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ftCPF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JPasswordField pfSenha;
    // End of variables declaration//GEN-END:variables

    @Override
    public void btLoginActionPerformed(ActionEvent e){
        ContaVO conta = null;
        try {
            String cpf = ftCPF.getText();
            String senha = new String(pfSenha.getPassword());

            ContaRN contaRN = new ContaRN();
            conta = contaRN.autenticarRN(cpf, senha);
            if (conta != null) {
                JOptionPane.showMessageDialog(null, "LOGIN REALIZADO COM SUCESSO!", "LOGIN", JOptionPane.INFORMATION_MESSAGE);
                TelaPrincipalVisao logado = new TelaPrincipalVisao(conta);                               
                dispose();
                logado.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "USUARIO OU SENHA INCORRETOS!", "LOGIN INCORRETO", JOptionPane.INFORMATION_MESSAGE);
                }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro no Login" + ex.getMessage() , "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void btCadastroActionPerformed(ActionEvent e) {
        int confirm;
        confirm = JOptionPane.showConfirmDialog(null, "Deseja continuar para o cadastro?", "Tela cadastro", JOptionPane.OK_CANCEL_OPTION);
        if (confirm == 0){
            MenuCadastro cadastro = new MenuCadastro();
            dispose();
            cadastro.setVisible(true);
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        Object escolha = e.getSource();
        
        if (escolha == btLogin) {
            btLoginActionPerformed(e);
        } else {
            btCadastroActionPerformed(e);
        }
    }

}
