package visao.menus;
//https://viacep.com.br
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import VO.ContaVO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import regraNegocio.ContaRN;

/**
 *
 * @author narja
 */
public class MenuCadastro extends FormTemplateMenus implements ActionListener {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuCadastro.class.getName());
    MenuInicial MenuInicial;

    public void resetCad(){
        //Habilitar
        ftCep.setEnabled(true);
        tfRua.setEnabled(true);
        tfBairro.setEnabled(true);
        //Limpar
        tfTitular.setText("");
        ftCpf.setText("");
        tfEmail.setText("");
        ftCep.setText("");
        tfCidade.setText("");
        tfRua.setText("");
        tfBairro.setText("");
        tfNumero.setText("");
        tfComplemento.setText("");
        ftSaldo.setText("");
        pfSenha.setText("");
        pfConfirmSenha.setText("");
        cbUF.setSelectedIndex(0);
        
        lbStatusCEP.setText("Status CEP");
        lbStatusSenha.setText("Insira a senha");
        btCadastro.setEnabled(false);
        pbProgressoCEP.setIndeterminate(false);
    }
    
    public ContaVO criarConta(String senha, double saldo){
        
        ContaVO novaConta = new ContaVO();
        
        novaConta.setTitular(tfTitular.getText());
        novaConta.setCpf(ftCpf.getText());
        novaConta.setEmail(tfEmail.getText());
        novaConta.setSenha(senha);
        novaConta.setCep(ftCep.getText());
        novaConta.setRua(tfRua.getText());
        novaConta.setBairro(tfBairro.getText());
        novaConta.setCidade(tfCidade.getText());
        novaConta.setEstado(cbUF.getSelectedItem().toString());
        novaConta.setNumeroCasa(tfNumero.getText());
        novaConta.setComplemento(tfComplemento.getText());
        novaConta.setSaldo(saldo);
        
        return novaConta;
    }
    
    public MenuCadastro() {
        initComponents();
        btCadastro.setEnabled(false);
        
        cbUF.setEnabled(false);
        tfCidade.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgConta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfTitular = new javax.swing.JTextField();
        ftCpf = new javax.swing.JFormattedTextField();
        tfEmail = new javax.swing.JTextField();
        cbCorrente = new javax.swing.JRadioButton();
        cbPoupanca = new javax.swing.JRadioButton();
        ftCep = new javax.swing.JFormattedTextField();
        tfCidade = new javax.swing.JTextField();
        cbUF = new javax.swing.JComboBox<>();
        tfRua = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        tfNumero = new javax.swing.JTextField();
        tfComplemento = new javax.swing.JTextField();
        pfSenha = new javax.swing.JPasswordField();
        pfConfirmSenha = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lbStatusSenha = new javax.swing.JLabel();
        lbStatusCEP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ftSaldo = new javax.swing.JFormattedTextField();
        pbProgressoCEP = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CADASTRO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Titular*:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("CPF*:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("E-mail*:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Conta*:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("CEP*:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Rua*:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Complemento:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Número*:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Cidade:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("UF:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Senha*:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Confirme a senha*:");

        tfTitular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTitular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTitularFocusGained(evt);
            }
        });

        try {
            ftCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftCpfFocusGained(evt);
            }
        });

        tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEmailFocusGained(evt);
            }
        });

        bgConta.add(cbCorrente);
        cbCorrente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCorrente.setText("CORRENTE");

        bgConta.add(cbPoupanca);
        cbPoupanca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbPoupanca.setText("POUPANÇA");

        try {
            ftCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftCepFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftCepFocusLost(evt);
            }
        });

        tfCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCidadeFocusGained(evt);
            }
        });

        cbUF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha...", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MS", "MT", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        tfRua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfRua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfRuaFocusGained(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Bairro*:");

        tfBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfBairroFocusGained(evt);
            }
        });

        tfNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNumeroFocusGained(evt);
            }
        });

        tfComplemento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfComplemento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfComplementoFocusGained(evt);
            }
        });

        pfSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pfConfirmSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pfConfirmSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pfConfirmSenhaKeyReleased(evt);
            }
        });

        lbStatusSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbStatusSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStatusSenha.setText("STATUS SENHA");

        lbStatusCEP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbStatusCEP.setText("STATUS ENDEREÇO");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Saldo inicial*:");

        ftSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbCorrente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ftCep, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbStatusSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pfConfirmSenha)
                            .addComponent(pfSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(ftSaldo))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbStatusCEP)
                .addGap(53, 53, 53)
                .addComponent(pbProgressoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbCorrente)
                    .addComponent(cbPoupanca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbStatusCEP)
                    .addComponent(pbProgressoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ftSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfConfirmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbStatusSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //
    private void pfConfirmSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfConfirmSenhaKeyReleased
        String s1 = new String(pfSenha.getPassword());
        String s2 = new String(pfConfirmSenha.getPassword());

        if (s1.equals(s2)) {
            lbStatusSenha.setText("Senhas conferem!️");
            lbStatusSenha.setForeground(java.awt.Color.GREEN); // Texto Verde
            btCadastro.setEnabled(true);

        } else {
            lbStatusSenha.setText("Senhas não conferem!");
            lbStatusSenha.setForeground(java.awt.Color.RED); // Texto Vermelho
            btCadastro.setEnabled(false);
        }
        }

        @Override
        public void btLoginActionPerformed(ActionEvent e) {
            int confirm;
            confirm = JOptionPane.showConfirmDialog(null, "Deseja continuar para a tela de Login?", "Tela Login", JOptionPane.OK_CANCEL_OPTION);
            if (confirm == 0){
                MenuLogin login = new MenuLogin();
                login.setVisible(true);
                dispose();
            }
        }

        @Override
        public void btCadastroActionPerformed(ActionEvent e) {
            String s1 = new String(pfSenha.getPassword());
            try{
                double saldoInicial = 0.0;
                String valorTexto = ftSaldo.getText(); 
                if (!valorTexto.trim().isEmpty()) {
                    valorTexto = valorTexto.replace(".", "").replace(",", ".");
                    saldoInicial = Double.parseDouble(valorTexto);
                }

                ContaVO novaConta = new ContaVO();
                
                novaConta = criarConta(s1, saldoInicial);      

                if (cbCorrente.isSelected()) novaConta.setTipoConta("CORRENTE");
                else if (cbPoupanca.isSelected()) novaConta.setTipoConta("POUPANÇA");

                ContaRN rn = new ContaRN();

                if (rn.validarDadosCadastro(novaConta) == false) {
                    JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios!", "Erro", JOptionPane.WARNING_MESSAGE);
                }else{
                    ContaVO sucesso = rn.cadastrar(novaConta);//COLOCAR CONTA COMO STRING PARA DAR OS PROVAVEIS ERROS

                    if (sucesso != null) {
                        JOptionPane.showMessageDialog(this, "Conta " + novaConta.getNumeroConta() + " criada com sucesso!");
                        resetCad();                       
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao salvar no banco.");
                    }
                }
            } catch (NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "APENAS NUMEROS! Erro:" + ex.getMessage() , "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERRO: " + ex.getMessage() , "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            Object escolha = e.getSource();

            if (escolha == btLogin) {
                btLoginActionPerformed(e);
            } else {
                btCadastroActionPerformed(e);
            }

    }//GEN-LAST:event_pfConfirmSenhaKeyReleased

    private void tfTitularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTitularFocusGained
        tfTitular.setText("");
    }//GEN-LAST:event_tfTitularFocusGained

    private void ftCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftCpfFocusGained
        ftCpf.setText("");
    }//GEN-LAST:event_ftCpfFocusGained

    private void tfEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEmailFocusGained
        tfEmail.setText("");
    }//GEN-LAST:event_tfEmailFocusGained

    private void ftCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftCepFocusLost
        System.out.println("Entrou");
        String cep = ftCep.getText();
        String cepLimpo = cep.replaceAll("[^0-9]", "");
        
        if (cepLimpo != null && !cep.trim().isEmpty()){
            System.out.println("Entrou 2");
            Thread thread;
            thread = new Thread(new Runnable() {
                @Override
                public void run() {
                    try {                       
                        ContaRN rn = new ContaRN();
                        ftCep.setEnabled(false);
                        tfRua.setEnabled(false);
                        tfBairro.setEnabled(false);
                        cbUF.setEnabled(false);
                        tfCidade.setEnabled(false);
                        
                        lbStatusCEP.setText("Buscando CEP");
                        pbProgressoCEP.setIndeterminate(true);
                        VO.CepVO cepEncontrado = rn.buscarCep(cepLimpo);
                        
                        //segunda thread para ele não travar caso alguem mexa na primeira
                        java.awt.EventQueue.invokeLater(new Runnable() {//uma fila, esta pedindo para ele realizar no fim
                            @Override
                            public void run() {    
                                if (cepEncontrado != null) {
                                    tfRua.setText(cepEncontrado.getLogradouro());
                                    tfBairro.setText(cepEncontrado.getBairro());
                                    tfCidade.setText(cepEncontrado.getCidade());
                                    cbUF.setSelectedItem(cepEncontrado.getUf());
                                    lbStatusCEP.setText("Encontramos o CEP!");
                                    pbProgressoCEP.setIndeterminate(false);
                                    ftCep.setEnabled(true);
                                    tfRua.setEnabled(true);
                                    tfBairro.setEnabled(true);
                                    
                                } else {
                                    lbStatusCEP.setText("CEP não encontrado!");
                                    pbProgressoCEP.setIndeterminate(false);
                                    ftCep.setEnabled(true);
                                    tfRua.setEnabled(true);
                                    tfBairro.setEnabled(true);
                                    cbUF.setEnabled(true);
                                    tfCidade.setEnabled(true);
                                }
                            }
                        });
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "ERRO!" + ex.getMessage() , "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }); thread.start();
        }
    }//GEN-LAST:event_ftCepFocusLost

    private void ftCepFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftCepFocusGained
        ftCep.setText("");
        lbStatusCEP.setText("Status CEP");
    }//GEN-LAST:event_ftCepFocusGained

    private void tfCidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCidadeFocusGained
        tfCidade.setText("");
    }//GEN-LAST:event_tfCidadeFocusGained

    private void tfRuaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfRuaFocusGained
        tfRua.setText("");
    }//GEN-LAST:event_tfRuaFocusGained

    private void tfBairroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBairroFocusGained
        tfBairro.setText("");
    }//GEN-LAST:event_tfBairroFocusGained

    private void tfNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNumeroFocusGained
        tfNumero.setText("");
    }//GEN-LAST:event_tfNumeroFocusGained

    private void tfComplementoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfComplementoFocusGained
        tfComplemento.setText("");
    }//GEN-LAST:event_tfComplementoFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgConta;
    private javax.swing.JRadioButton cbCorrente;
    private javax.swing.JRadioButton cbPoupanca;
    private javax.swing.JComboBox<String> cbUF;
    private javax.swing.JFormattedTextField ftCep;
    private javax.swing.JFormattedTextField ftCpf;
    private javax.swing.JFormattedTextField ftSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbStatusCEP;
    private javax.swing.JLabel lbStatusSenha;
    private javax.swing.JProgressBar pbProgressoCEP;
    private javax.swing.JPasswordField pfConfirmSenha;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfRua;
    private javax.swing.JTextField tfTitular;
    // End of variables declaration//GEN-END:variables

}